### PR TITLE
Started porting some of the canopen code to ROS2

### PR DESCRIPTION
**Pull request by samiamlabs**
Hi, 

I started working on porting some of the CANopen code to ROS2.

Currently getting an emergency message when calling the 'init' service on canopen_chain_node with the hardware I'm using to test it.

I moved the .srv files from canopen_chain_node to a new canopen_msgs package as well.

canopen_chain_node compiles, runs with a launch file can read parameters from a .yaml file.

### CODE REVIEW

**Comment by samiamlabs** [comment]
### Here is a the teminal output for the current issue I'm having:
```
[INFO] [launch]: process[canopen_chain_node-1]: started with pid [11235]
[INFO] [canopen_driver.canopen_chain_node]: hardware_id: I/0 1
[INFO] [canopen_driver.canopen_chain_node]: reset_errors_before_recover: 1
[INFO] [canopen_driver.canopen_chain_node]: can device: can0
[INFO] [canopen_driver.canopen_chain_node]: driver_plugin: socketcan_interface/SocketCANInterface
[INFO] [canopen_driver.canopen_chain_node]: loopback: 0
[INFO] [canopen_driver.canopen_chain_node]: master_allocator: canopen_master/SimpleMasterAllocator
[INFO] [canopen_driver.canopen_chain_node]: interval_ms: 0
[INFO] [canopen_driver.canopen_chain_node]: update_ms: 10
[WARN] [canopen_driver.canopen_chain_node]: heartbeat_msg not specified, using 77f#05
[INFO] [canopen_driver.canopen_chain_node]: heartbeat_msg: 77f#05
[WARN] [canopen_driver.canopen_chain_node]: heartbeat_rate not specified, using 10.0
[INFO] [canopen_driver.canopen_chain_node]: heartbeat_rate: 10.000000
[INFO] [canopen_driver.canopen_chain_node]: not producing heartbeat!
[INFO] [canopen_driver.canopen_chain_node]: default eds_pkg: canopen_chain_node
[INFO] [canopen_driver.canopen_chain_node]: default eds_file: test/eds/ISD860.eds
[INFO] [canopen_driver.canopen_chain_node]: node1 node id: 8
[INFO] [canopen_driver.canopen_chain_node]: node1 eds_file: test/eds/ISD860.eds
[INFO] [canopen_driver.canopen_chain_node]: node1 eds_pkg: canopen_chain_node
[INFO] [canopen_driver.canopen_chain_node]: node1 eds full path: /opt/dredgebot_ws/install/canopen_chain_node/share/canopen_chain_node/test/eds/ISD860.eds
[INFO] [canopen_driver.canopen_chain_node]: no objects to be published were spiecified
[INFO] [canopen_driver.canopen_chain_node]: Initializing XXX
EMCY: 88#0000000000000000
```
### And a wireshark trace:
```
No.     Time           Source                Destination           Protocol Length Info
      1 0.000000                                                   CANopen  9      NMT Error Control: Boot-up [0x8]

Frame 1: 9 bytes on wire (72 bits), 9 bytes captured (72 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000708
    Type: NMT Error Control
        0... .... = Reserved/Toggle: 0
        .000 0000 = State: Boot-up (0x00)

No.     Time           Source                Destination           Protocol Length Info
      2 17.586464                                                  CANopen  10     NMT: Reset communication [0x8]

Frame 2: 10 bytes on wire (80 bits), 10 bytes captured (80 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000000
    Type: NMT
        1000 0010 = Command specifier: Reset communication (0x82)
        Node-ID: 0x08

No.     Time           Source                Destination           Protocol Length Info
      3 17.587596                                                  CANopen  9      NMT Error Control: Boot-up [0x8]

Frame 3: 9 bytes on wire (72 bits), 9 bytes captured (72 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000708
    Type: NMT Error Control
        0... .... = Reserved/Toggle: 0
        .000 0000 = State: Boot-up (0x00)

No.     Time           Source                Destination           Protocol Length Info
      4 17.587767                                                  CANopen  16     Default-SDO (rx): Initiate download request

Frame 4: 16 bytes on wire (128 bits), 16 bytes captured (128 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000608
    Type: Default-SDO (rx)
        SDO command byte: 0x2b, Client command specifier: Initiate download request, Expedited transfer, Data set size indicated
        OD main-index: Producer heartbeat time (0x1017)
        OD sub-index: 0x00
        Data: 00000000

No.     Time           Source                Destination           Protocol Length Info
      5 17.588819                                                  CANopen  16     Default-SDO (tx): Initiate download response

Frame 5: 16 bytes on wire (128 bits), 16 bytes captured (128 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000588
    Type: Default-SDO (tx)
        SDO command byte: 0x60, Server command specifier: Initiate download response
        OD main-index: Producer heartbeat time (0x1017)
        OD sub-index: 0x00
        Reserved: 00000000

No.     Time           Source                Destination           Protocol Length Info
      6 17.590073                                                  CANopen  10     NMT: Start remote node [0x8]

Frame 6: 10 bytes on wire (80 bits), 10 bytes captured (80 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000000
    Type: NMT
        0000 0001 = Command specifier: Start remote node (0x01)
        Node-ID: 0x08

No.     Time           Source                Destination           Protocol Length Info
      7 17.590619                                                  CANopen  10     PDO1 (tx)

Frame 7: 10 bytes on wire (80 bits), 10 bytes captured (80 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000188
    Type: PDO1 (tx)
        Data: 4002

No.     Time           Source                Destination           Protocol Length Info
      8 17.590700                                                  CANopen  11     PDO2 (tx)

Frame 8: 11 bytes on wire (88 bits), 11 bytes captured (88 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000288
    Type: PDO2 (tx)
        Data: 400200

No.     Time           Source                Destination           Protocol Length Info
      9 19.590251                                                  CANopen  16     Default-SDO (rx): Initiate upload request

Frame 9: 16 bytes on wire (128 bits), 16 bytes captured (128 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000608
    Type: Default-SDO (rx)
        SDO command byte: 0x40, Client command specifier: Initiate upload request
        OD main-index: Error register (0x1001)
        OD sub-index: 0x00
        Reserved: 00000000

No.     Time           Source                Destination           Protocol Length Info
     10 19.590843                                                  CANopen  16     Default-SDO (tx): Initiate upload response

Frame 10: 16 bytes on wire (128 bits), 16 bytes captured (128 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000588
    Type: Default-SDO (tx)
        SDO command byte: 0x4f, Server command specifier: Initiate upload response, Expedited transfer, Data set size indicated
        OD main-index: Error register (0x1001)
        OD sub-index: 0x00
        Data: 00000000

No.     Time           Source                Destination           Protocol Length Info
     11 19.590911                                                  CANopen  16     Default-SDO (rx): Initiate download request

Frame 11: 16 bytes on wire (128 bits), 16 bytes captured (128 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000608
    Type: Default-SDO (rx)
        SDO command byte: 0x2f, Client command specifier: Initiate download request, Expedited transfer, Data set size indicated
        OD main-index: Pre-defined error field (0x1003)
        OD sub-index: 0x00
        Data: 00000000

No.     Time           Source                Destination           Protocol Length Info
     12 19.591454                                                  CANopen  16     EMCY

Frame 12: 16 bytes on wire (128 bits), 16 bytes captured (128 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000088
    Type: EMCY
        Error code: Error reset or no error (0x0000)
        Error register: 0x00
        Manufacturer specific error field: 0000000000

No.     Time           Source                Destination           Protocol Length Info
     13 19.591584                                                  CANopen  16     Default-SDO (tx): Initiate download response

Frame 13: 16 bytes on wire (128 bits), 16 bytes captured (128 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000588
    Type: Default-SDO (tx)
        SDO command byte: 0x60, Server command specifier: Initiate download response
        OD main-index: Pre-defined error field (0x1003)
        OD sub-index: 0x00
        Reserved: 00000000

No.     Time           Source                Destination           Protocol Length Info
     14 19.591733                                                  CANopen  10     NMT: Stop remote node [0x8]

Frame 14: 10 bytes on wire (80 bits), 10 bytes captured (80 bits) on interface 0
Controller Area Network
CANopen
    COB-ID: 0x00000000
    Type: NMT
        0000 0010 = Command specifier: Stop remote node (0x02)
        Node-ID: 0x08
```

**Comment by samiamlabs** [comment]
Figured out the problem. I had removed a couple of ```return``` statements in the ```handle_init``` function by accident when I meant to only remove the return value :P

Seems to be working now, but have not had time to do any much testing yet.

**Comment by JWhitleyWork** [comment]
@samiamlabs - So, I know this is going to be a train wreck but, could you possibly add in all of the lint options too? e.g.: 

    if(BUILD_TESTING)
      find_package(ament_lint_auto REQUIRED)
      ament_lint_auto_find_test_dependencies()
    endif()

and in package.xml:

    <test_depend>ament_lint_auto</test_depend>
    <test_depend>ament_lint_common</test_depend>

Linting definitely took me the longest in the conversion process but I believe it's very necessary for maintainability and we might as well do it now, since we're rewriting much of the code anyway, right?

**Comment by samiamlabs** [comment]
I used the ament_uncrustify terminal tool to remove the uncrustify errors for canopen_chain_node.
ament_cpplint is rather picky though... 

Do you happen to know what linters are run by lint_auto and lint_common?

Started working on canopen_motor_node, and was planning to make sure that it passes the uncrustify linting as well.

I mostly modified the CMake code for canopen_master and canopen_402 so have not fixed any linting errors for those packages.

Do you know of a clean way of show the liner errors from the build tests in the terminal? Looking in log files does not seem like a great workflow...

**Comment by JWhitleyWork** [comment]
`ament_lint_common` adds dependencies on the following:

	ament_cmake_copyright
	ament_cmake_cppcheck
	ament_cmake_cpplint
	ament_cmake_flake8
	ament_cmake_lint_cmake
	ament_cmake_pep257
	ament_cmake_uncrustify
	ament_cmake_xmllint

`flake8` and `pep257` only apply to Python but the others cover all file types in a typical package. `ament_lint_auto` automatically finds the packages that package.xml depends on in `<test_depend></test_depend>` tags and adds them as tests.

Unfortunately, I really haven't found a better way than to run `colcon test-results` and then `cat` the XML files.

**Comment by samiamlabs** [comment]
Ok.

I will add the liner options to ```canopen_chain_node``` this week.  Will do that for ```canopen_motor_node``` when I get to it as well.

As I have not really needed to modify the code in ```canopen_master``` to get it working I think it makes more sense to add the linter options when removing boost dependencies. Will probably not start working on that untill I have managed to control a motor with the ROS2 port.

Do you want to wait with merging until the linter errors are fixed?

**Comment by JWhitleyWork** [comment]
I'm OK with merging them now without the linter changes. It's really hard to read PRs with the linter changes included so it's actually better to do the functional changes first, then linter clean-up as a separate PR.

**Comment by JWhitleyWork** [comment]
Give me a bit to review and I'll get it merged once I've built and tested.

**Comment by samiamlabs** [comment]
Great. Note that I added a "from source" dependency for ```diagnostics``` and a ros_dependencies.repos file. Hopefully diagnostics will be released for ROS2 soon so we can remove that. https://discourse.ros.org/t/diagnostic-aggregator-and-diagnostic-updater-porting-to-ros2/6382/16

**Comment by JWhitleyWork** [comment]
Everything looks good for now. I've built it locally (after running `vcs import < ros_canopen/ros_dependencies.repos`) and it looks good.

**Pull request merged**
